### PR TITLE
#95 latex export

### PR DESCRIPTION
**Pull request by adrianjost**
# Ticket
#95 

# Description
Markdown export isn't enough? We now support Latex aas well :D (except colored text)

# Is everything tested?
Jup, except the layout component. I'm waiting for the new Markdown tests from the refactoring did by @malte-b to write it more uniform.

# Is it release relevant?
You love the our markdown export but are a geek that enjoys latex as well? We are happy to announce that we now support LaTEX as well. Feel free to try and give us feedback because we are noobies to LaTEX and aren't sure if we did everything right.

# Screenshot
not really

# coding style checks
 - [x] no external ressources needed
 - [x] coding standards 
    - [x] no `.` at the end of your function
    - [x] an empty line between functionname and code (except accessors)
    - [x] cascades wherever possible
    - [x] space around `@`, binary operators such as `+` or `<=` and after `^`
    - [x] no `or` stands alone in a line 
    - [x] variable definitions...
      - [ ] ... have an space before/after the `|` symbol
      - [ ] ... have a blank line above and under
      - [ ] ... are used as few as possible   
   - [x] static values are stored on class Side
   - [x] every function has a category
   - [x] don't use magic numbers (and strings)!
 - [ ] basic UX
   - [ ] UI is intuitive to use (tested by the reviewer! reject if not)
   - [ ] ...

 ```smalltalk
example: aValue
   
   | variable |
   
   variable := 5.
   self myObject 
       value: aValue + variable;
       color: Color red.
   self otherMethod
   ```

### CODE REVIEW

**Comment by adrianjost** [comment]
as tom mentioned to me, travis `OrderedCollection new` is broken at the moment. We can merge anyway when someone approves it.

**Comment by malte-b** [comment]
Doesn't render correctly on my machine. Checked with ShareLaTex

**Comment by malte-b** [comment]
If you want to implement colors with html codes you have to import: `\usepackage[dvipsnames]{xcolor}`
for my example you also would have to define the color: `\definecolor{custom1}{HTML}{FF0000}
This is a \textcolor{custom1}{test}`

**Comment by malte-b** [comment]
Also you can now make the tests more uniform with the refactored tests as they are ready to merge

**Comment by malte-b** [comment]
And special characters like <> are also exported wrongly as you can see in the screenshot

**Comment by adrianjost** [comment]
@malte-b do you have any idea how we could implement the color replacing? At the moment we try to replace html codes. But for colors we need some regex stuff and I wasn't able to figure out how to get the matching groups from the regex. 

```smalltalk
"<font color='#0000FF'>blue</font>"
"to:"
"'\definecolor{00F9DE}{HTML}{00F9DE}\textcolor{00F9DE}{text}'"

| regex text |
regex := '.*<font color="#([0-9a-fA-F]{6})">(.*).*'.
text := '<font color="#0000FF">blue</font>'.

text allRegexMatches: regex
"emtpy result :("
```

**Comment by malte-b** [comment]
i think you can leave lowercase letters out of your regex because they can't appear in html color codes. other than that i don't know why you regex isn't working.

**Comment by adrianjost** [comment]
@malte-b forget about my previous comment. I rewritten everything and it should work now (at least I hope so).
Could you please test it again as fast as possible so that we can merge it before our meeting today? :)

**Pull request merged**
